export interface StoreEvents {
  // Chats
  GET_CHATS: string;
  GET_CHATS_SUCCESS: string;
  GET_CHATS_FAILURE: string;
  CREATE_CHAT_SUCCESS: string;
  CREATE_CHAT_FAILURE: string;
  CHAT_UPDATED_SUCCESS: string;
  CHAT_UPDATED_FAILURE: string;
  DELETE_CHAT_SUCCESS: string;
  DELETE_CHAT_FAILURE: string;
  ADD_USER_TO_CHAT_SUCCESS: string;
  ADD_USER_TO_CHAT_FAILURE: string;
  DELETE_USER_FROM_CHAT_SUCCESS: string;
  DELETE_USER_FROM_CHAT_FAILURE: string;
  // User
  GET_USER_DATA_SUCCESS: string;
  GET_USER_DATA_FAILURE: string;
  USER_UPDATED_SUCCESS: string;
  USER_UPDATED_FAILURE: string;
  USER_AVATAR_CHANGED_SUCCESS: string;
  USER_AVATAR_CHANGED_FAILURE: string;
  GET_USER_SUCCESS: string;
  GET_USER_FAILURE: string;
  PASSWORD_CHANGE_SUCCESS: string;
  PASSWORD_CHANGE_FAILURE: string;
  // Auth
  REGISTER_SUCCESS: string;
  REGISTER_FAILURE: string;
  LOGIN_USER_SUCCESS: string;
  LOGIN_USER_FAILURE: string;
  LOGOUT_USER_SUCCESS: string;
  LOGOUT_USER_FAILURE: string;

  INIT: string;
}

export const STORE_EVENTS = {
    // Chats
    GET_CHATS: 'GET_CHATS',
    GET_CHATS_SUCCESS: 'GET_CHATS_SUCCESS',
    GET_CHATS_FAILURE: 'GET_CHATS_FAILURE',
    CREATE_CHAT_SUCCESS: 'CREATE_CHAT_SUCCESS',
    CREATE_CHAT_FAILURE: 'CREATE_CHAT_FAILURE',
    CHAT_UPDATED_SUCCESS: 'CHAT_UPDATED_SUCCESS',
    CHAT_UPDATED_FAILURE: 'CHAT_UPDATED_FAILURE',
    DELETE_CHAT_SUCCESS: 'DELETE_CHAT_SUCCESS',
    DELETE_CHAT_FAILURE: 'DELETE_CHAT_FAILURE',
    ADD_USER_TO_CHAT_SUCCESS: 'ADD_USER_TO_CHAT_SUCCESS',
    ADD_USER_TO_CHAT_FAILURE: 'ADD_USER_TO_CHAT_FAILURE',
    DELETE_USER_FROM_CHAT_SUCCESS: 'DELETE_USER_FROM_CHAT_SUCCESS',
    DELETE_USER_FROM_CHAT_FAILURE: 'DELETE_USER_FROM_CHAT_FAILURE',
    // User
    GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
    GET_USER_DATA_FAILURE: 'GET_USER_DATA_FAILURE',
    USER_UPDATED_SUCCESS: 'USER_UPDATED_SUCCESS',
    USER_UPDATED_FAILURE: 'USER_UPDATED_FAILURE',
    USER_AVATAR_CHANGED_SUCCESS: 'USER_AVATAR_CHANGED_SUCCESS',
    USER_AVATAR_CHANGED_FAILURE: 'USER_AVATAR_CHANGED_FAILURE',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',
    PASSWORD_CHANGE_SUCCESS: 'PASSWORD_CHANGE_SUCCESS',
    PASSWORD_CHANGE_FAILURE: 'PASSWORD_CHANGE_FAILURE',
    // Auth
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
    LOGOUT_USER_FAILURE: 'LOGOUT_USER_FAILURE',

    INIT: 'INIT'
} as StoreEvents
